
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MOD = 22;
  public static final int READ = 11;
  public static final int IDENT = 29;
  public static final int SEMICOLON = 2;
  public static final int ELSE = 9;
  public static final int PLUS = 18;
  public static final int STRINGCONST = 30;
  public static final int GTQ = 24;
  public static final int COMP = 16;
  public static final int WHILE = 10;
  public static final int END = 7;
  public static final int INTCONST = 17;
  public static final int IF = 8;
  public static final int GT = 28;
  public static final int LE = 27;
  public static final int WRITE = 12;
  public static final int BEGIN = 6;
  public static final int TYPE = 14;
  public static final int COMMA = 3;
  public static final int MULT = 20;
  public static final int EOF = 0;
  public static final int DIV = 21;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int EQ = 25;
  public static final int ASSIGN = 13;
  public static final int LEQ = 23;
  public static final int RPAR = 5;
  public static final int FLOATCONST = 31;
  public static final int NEQ = 26;
  public static final int BINOP = 15;
  public static final int LPAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COMMA",
  "LPAR",
  "RPAR",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "WHILE",
  "READ",
  "WRITE",
  "ASSIGN",
  "TYPE",
  "BINOP",
  "COMP",
  "INTCONST",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "LEQ",
  "GTQ",
  "EQ",
  "NEQ",
  "LE",
  "GT",
  "IDENT",
  "STRINGCONST",
  "FLOATCONST"
  };
}

